### ISSUE TITLE
Telegram token stored

### ISSUE THREAD

**Issue by ArturLukianov** [yogeshwaran01/telebot#1]
Hi, @yogeshwaran01 !
Your telegram token is stored in config.py, and anybody can access it. You should remove it from repository and hide commit with this file. As a suggestion, you can move it to configuration file and add this file to your .gitignore

```sh
curl https://api.telegram.org/bot1303637043:AAHTdp5ge5F6GWu8FPtax2dJUpHQFe3MxwI/getMe
```
```json
{"ok":true,"result":{"id":1303637043,"is_bot":true,"first_name":"Excel","username":"excelyo_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false}}
```

**Comment by yogeshwaran01** [comment]
Thank you, @ArturLukianov 
 As per suggestion, I moved the configuration file to .gitignore and token is changed
